### PR TITLE
Assignment 1: Unused Loop Variable - Mikhail Rodionychev

### LINKED ISSUE #6: Unused Loop Variable
Report loops (`AstStatementWhile` and `AstStatementUntil`) that don't use the loop variable. To simplify the implementation, it is suggested to consider only loops that use a local variable in the condition and ensure that there are uses of that identifier in the body of the loop.

## Why is it bad?
This is a special case of the unbounded loop problem that can be problematic for several reasons:
* Unexpected Behavior: Without a defined termination, loops can lead to unpredictable contract behavior and make debugging difficult.
* Out-of-gas Attacks: Continuous looping without termination can lead to out-of-gas attacks.
* DoS Attacks: Malicious actors can exploit unbounded loops to create denial-of-service attacks, impacting the contract's availability.

## Example
```
let a: Int = 0;
while (a < 10) { // Bad: 'a' is not accessed within the loop
  self.do_something();
}
```

Use instead:
```
let a: Int = 0;
while (a < 10) {
  self.do_something();
  a += 1;
}
```

### PR DESCRIPTION
**Pull request by Taifin**
Closes #6

### CODE REVIEW

**Review by jubnzv — CHANGES_REQUESTED** [review]
`yarn fix-all` could help fixing the formatting.

File: assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+  }
+
+  /**
+   * Traverse loop statements of the compilation unit for unused variable check.
+   */
+  private checkLoopStatements(cu: CompilationUnit) {
+    Array.from(cu.ast.getStatements()).forEach((statement) => {
+      if (
+        statement.kind === "statement_while" ||
+        statement.kind == "statement_until"
```
Comment (jubnzv) [inline assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts:52]: nit: Why a different equals operation here?

File: assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+    );
+  }
+
+  /**
+   * For a given statement and a variable identifier, determine if such a variable is used in the statement.
+   */
+  private isVariableUsedInStatement(
+    variableId: AstId,
+    statement: AstStatement,
+  ): number {
```
Comment (jubnzv) [inline assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts:130]: Why don't return a boolean here?

**Review by jubnzv — CHANGES_REQUESTED** [review]
It works correctly. Let's adjust the implementation a bit before merging.

File: assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts (hunk 1 above)
Comment (Taifin) [reply assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts:52]: Fixed

File: assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts (hunk 2 above)
Comment (Taifin) [reply assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts]: `foldExpressions` for while visited the condition too and was finding extra usages of the variable, so I switched to counting instead of checking for presence. Fixed now anyway

File: assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts (hunk 1 above)
Comment (jubnzv) [reply assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts:52]: Well, actually we should prefer `==` in TypeScript to avoid surprises related to dynamic typing. But it will work here, so nevermind.

**Review by jubnzv — APPROVED** [review]
